services:
  postgres:
    image: "postgres:16-alpine"
    ports:
      - "5433:5432"
    volumes:
      - adopet_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: adopet
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adopet-api:
    image: "docker.io/library/adopet-api:0.0.1-SNAPSHOT"
    environment:
      POSTGRES_DB: adopet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SERVER_PORT: 9090
    depends_on:
      - postgres

volumes:
  - adopet_data: