services:
  postgres:
    container_name: kopet-db
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    volumes:
      - adopet_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: adopet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - kopet-bridge

  adopet-api:
    container_name: kopet-api
    image: docker.io/library/adopet-api:0.0.1-SNAPSHOT
    environment:
      POSTGRES_DB: adopet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: 172.20.0.1
      POSTGRES_PORT: 5433
      SERVER_PORT: 9090
    depends_on:
      - postgres
    ports:
      - "9090:9090"
    networks:
      - kopet-bridge


volumes:
  adopet_data:

networks:
  kopet-bridge:
    driver: bridge