server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: kopet-api
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/adopet
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true


  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/adopet

application:
  security:
    jwt:
      secret-key: 25432A462D4A614E645267556B58703273357638792F413F4428472B4B625065
      expiration: 3600000
      refresh-token:
        expiration: 86400000